### ISSUE TITLE
Program crashes when trying to load a saved Castle File

### ISSUE THREAD

**Issue by SestrenExsis** [MainMemory/SotNCastleEditor#1]
### Steps I took that produced the error:

1. I moved a few rooms around in Alchemy Lab (see picture below)
2. I saved the file
3. I closed the program
4. I restarted the program
5. I attempted to load the saved file

![image](https://github.com/user-attachments/assets/36de48c7-a3fd-41ee-a16d-fba9882e95d5)

After performing the steps above, I got the following error message:

```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at SotNData.MapPatch.Apply(CastleMap mapInfo) in D:\Documents\GitHub\SotNCastleEditor\SotNData\DataTypes.cs:line 505
   at SotNCastleEditor.MainForm.OpenFile(String filename) in D:\Documents\GitHub\SotNCastleEditor\SotNCastleEditor\MainForm.cs:line 104
   at SotNCastleEditor.MainForm.openToolStripMenuItem_Click(Object sender, EventArgs e) in D:\Documents\GitHub\SotNCastleEditor\SotNCastleEditor\MainForm.cs:line 94
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by MainMemory** [comment]
Are you sure you loaded a `.castle` file, and not a `.caspat` file? The error message there is saying that it was loading a patch file.

**Comment by MainMemory** [comment]
Never mind, I can see why you wouldn't know. I also see where the error is.
